spring.application.name=SerialComms


#Serial Configs

serial.baud-rate = 9600
serial.read-timeout = 3000
serial.write-timeout = 1000
serial.stop-bit = 1
serial.data-bit = 8

spring.datasource.url=jdbc:h2:mem:telemetrydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true