spring.application.name=SerialComms


#Serial configs

serial.baud-rate = 9600
serial.read-timeout = 3000
serial.write-timeout = 1000
serial.stop-bit = 1
serial.data-bit = 8
serial.pass-code = "ABC"
serial.start-machine-code = "s"
serial.stop-machine-code = "p"
serial.lock-machine-code = "L"
serial.speed-increase-code = "+"
serial.speed-decrease-code = "-"
#Database configs

spring.datasource.url=jdbc:h2:mem:telemetrydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true

#Alert config

alert.Adc-threshold = 900