spring.application.name=SerialComms
spring.profiles.active=sim


#Serial configs

serial.baud-rate = 9600
serial.read-timeout = 3000
serial.write-timeout = 1000
serial.stop-bit = 1
serial.data-bit = 8
serial.pass-code = ABC
serial.start-machine-code = s
serial.stop-machine-code = p
serial.lock-machine-code = L
serial.speed-increase-code = +
serial.speed-decrease-code = -


#Database configs

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true

#Alert config

alert.Adc-threshold = 900

#jwt

jwt.secret=${JWT_SECRET}