CREATE TABLE telemetry_entity(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count INTEGER,
    adc_value INTEGER,
    sample_period INTEGER,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL
);