CREATE TABLE telemetry_alert(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telemetry_entity_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    message VARCHAR(255),

    CONSTRAINT fk_telemetry_alert_telemetry_entity
    FOREIGN KEY(telemetry_entity_id)
    REFERENCES telemetry_entity(id)
);